var CODES = {};
//GET
CODES.OK_GET = 200;
CODES.FOUND_GET = 302;
CODES.NOT_MODIFIED_GET = 304;
//POST
CODES.OK_POST = 201;
CODES.ACCEPTED_POST = 202;
//PUT
CODES.OK_PUT = 201;
CODES.ACCEPTED_PUT = 202;
//DELETE
CODES.ACCEPTED_DELETE = 202;
CODES.OK_DELETE = 204;
//GENERAL
CODES.BAD_REQUEST = 400;
CODES.UNAUTHORIZED = 401;
CODES.FORBIDDEN = 403;
CODES.NOT_FOUND = 404;
CODES.INTERNAL_SERVER_ERROR = 500;

module.exports = CODES;